// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scanner} from '../models';
import {main} from '../models';

export function CancelDownload(arg1:string):Promise<boolean>;

export function CheckTargetDir(arg1:string):Promise<void>;

export function DirExists(arg1:string):Promise<boolean>;

export function DisableWindowsSleep():Promise<number>;

export function EnableWindowsSleep(arg1:number):Promise<void>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetAllFiles(arg1:string,arg2:scanner.Options):Promise<Array<string>>;

export function GetDownloaderStatus():Promise<main.DownloaderStatus>;

export function GetScannerStatus():Promise<main.ScannerStatus>;

export function GetSideloaderStatus():Promise<main.SideloaderStatus>;

export function InitSideload():Promise<Record<string, any>>;

export function IsSideloaderRunning():Promise<boolean>;

export function LaunchGame():Promise<void>;

export function LaunchStudio():Promise<void>;

export function LoadLocalMods():Promise<Record<string, any>>;

export function LoadSettings():Promise<Record<string, any>>;

export function Log(arg1:Array<any>):Promise<void>;

export function MoveFile(arg1:string,arg2:string):Promise<void>;

export function OpenFileSelector(arg1:string):Promise<string>;

export function OpenInFolder(arg1:string):Promise<void>;

export function Ping():Promise<string>;

export function ReadAllCharaNames(arg1:string):Promise<Array<string>>;

export function ReadDir(arg1:string):Promise<Array<string>>;

export function ReadPngForMod(arg1:string):Promise<Array<string>>;

export function ReadPngForShow(arg1:string):Promise<string>;

export function ReadPngImagesBatch(arg1:Array<string>):Promise<Array<scanner.PngImageResult>>;

export function ReadPngModsBatch(arg1:Array<string>):Promise<Array<scanner.PngModResult>>;

export function ReadPngNamesBatch(arg1:Array<string>):Promise<Array<scanner.PngNamesResult>>;

export function ReadPngPageDataBatch(arg1:Array<string>):Promise<Array<scanner.PngPageDataResult>>;

export function ReadZipMod(arg1:string):Promise<scanner.ModModel>;

export function ReadZipModBatch(arg1:Array<string>):Promise<scanner.ModModel>;

export function RunSideloader():Promise<void>;

export function SaveLocalMods(arg1:Record<string, any>):Promise<void>;

export function SaveSettings(arg1:Record<string, any>):Promise<void>;

export function SelectPath():Promise<string>;

export function SetProxy(arg1:main.ProxyInfo):Promise<void>;

export function StopSideloader():Promise<boolean>;

export function TriggerDownload(arg1:main.DownloadModel):Promise<void>;
