// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CheckTargetDir(arg1) {
  return window['go']['main']['App']['CheckTargetDir'](arg1);
}

export function DirExists(arg1) {
  return window['go']['main']['App']['DirExists'](arg1);
}

export function DisableWindowsSleep() {
  return window['go']['main']['App']['DisableWindowsSleep']();
}

export function EnableWindowsSleep(arg1) {
  return window['go']['main']['App']['EnableWindowsSleep'](arg1);
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function GetAllFiles(arg1, arg2) {
  return window['go']['main']['App']['GetAllFiles'](arg1, arg2);
}

export function GetDownloaderStatus() {
  return window['go']['main']['App']['GetDownloaderStatus']();
}

export function GetScannerStatus() {
  return window['go']['main']['App']['GetScannerStatus']();
}

export function GetSideloaderStatus() {
  return window['go']['main']['App']['GetSideloaderStatus']();
}

export function InitSideload() {
  return window['go']['main']['App']['InitSideload']();
}

export function IsSideloaderRunning() {
  return window['go']['main']['App']['IsSideloaderRunning']();
}

export function LaunchGame() {
  return window['go']['main']['App']['LaunchGame']();
}

export function LaunchStudio() {
  return window['go']['main']['App']['LaunchStudio']();
}

export function LoadLocalMods() {
  return window['go']['main']['App']['LoadLocalMods']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function MoveFile(arg1, arg2) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2);
}

export function OpenFileSelector(arg1) {
  return window['go']['main']['App']['OpenFileSelector'](arg1);
}

export function OpenInFolder(arg1) {
  return window['go']['main']['App']['OpenInFolder'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function ReadAllCharaNames(arg1) {
  return window['go']['main']['App']['ReadAllCharaNames'](arg1);
}

export function ReadDir(arg1) {
  return window['go']['main']['App']['ReadDir'](arg1);
}

export function ReadPngForMod(arg1) {
  return window['go']['main']['App']['ReadPngForMod'](arg1);
}

export function ReadPngForShow(arg1) {
  return window['go']['main']['App']['ReadPngForShow'](arg1);
}

export function ReadPngImagesBatch(arg1) {
  return window['go']['main']['App']['ReadPngImagesBatch'](arg1);
}

export function ReadPngModsBatch(arg1) {
  return window['go']['main']['App']['ReadPngModsBatch'](arg1);
}

export function ReadPngNamesBatch(arg1) {
  return window['go']['main']['App']['ReadPngNamesBatch'](arg1);
}

export function ReadPngPageDataBatch(arg1) {
  return window['go']['main']['App']['ReadPngPageDataBatch'](arg1);
}

export function ReadZipMod(arg1) {
  return window['go']['main']['App']['ReadZipMod'](arg1);
}

export function ReadZipModBatch(arg1) {
  return window['go']['main']['App']['ReadZipModBatch'](arg1);
}

export function RunSideloader() {
  return window['go']['main']['App']['RunSideloader']();
}

export function SaveLocalMods(arg1) {
  return window['go']['main']['App']['SaveLocalMods'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectPath() {
  return window['go']['main']['App']['SelectPath']();
}

export function SetProxy(arg1) {
  return window['go']['main']['App']['SetProxy'](arg1);
}

export function StopSideloader() {
  return window['go']['main']['App']['StopSideloader']();
}

export function TriggerDownload(arg1) {
  return window['go']['main']['App']['TriggerDownload'](arg1);
}
